### ISSUE TITLE
Zsh's prompt?

### ISSUE THREAD

**Issue by tmpm697** [hpcsc/dotfiles#1]
Reading your dotfiles but have no idea where you set your `prompt`, I saw a nice prompt in this articles: `https://pnguyen.io/posts/improve-productivity-with-fzf/` 

How can you achieve prompt to `~/P/C/teamcity`? @hpcsc

**Comment by hpcsc** [comment]
@tmpm697 I'm using [prezto](https://github.com/sorin-ionescu/prezto) framework for zsh. The prompt that you saw is `sorin` prompt from `prezto`
